version: '1.0'

services:
  db:
    image: rest:db
    container_name: rest_db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_DB: restdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - 5432:5432
    tty: true
      